export const CREATE_CHALLENGE_LOADING = "CREATE_CHALLENGE_LOADING";
export const CREATE_CHALLENGE_SUCCESS = "CREATE_CHALLENGE_SUCCESS";
export const CREATE_CHALLENGE_ERROR = "CREATE_CHALLENGE_ERROR";

export const GET_CHALLENGE_LOADING = "GET_CHALLENGE_LOADING";
export const GET_CHALLENGE_SUCCESS = "GET_CHALLENGE_SUCCESS";
export const GET_CHALLENGE_ERROR = "GET_CHALLENGE_ERROR";

export const ALL_CHALLENGE_LOADING = "ALL_CHALLENGE_LOADING";
export const ALL_CHALLENGE_SUCCESS = "ALL_CHALLENGE_SUCCESS";
export const ALL_CHALLENGE_ERROR = "ALL_CHALLENGE_ERROR";

export const CLAIM_CHALLENGE_LOADING = "CLAIM_CHALLENGE_LOADING";
export const CLAIM_CHALLENGE_SUCCESS = "CLAIM_CHALLENGE_SUCCESS";
export const CLAIM_CHALLENGE_ERROR = "CLAIM_CHALLENGE_ERROR";

export const FINISH_CHALLENGE_LOADING = "FINISH_CHALLENGE_LOADING";
export const FINISH_CHALLENGE_SUCCESS = "FINISH_CHALLENGE_SUCCESS";
export const FINISH_CHALLENGE_ERROR = "FINISH_CHALLENGE_ERROR";

export const DELETE_CHALLENGE_LOADING = "DELETE_CHALLENGE_LOADING";
export const DELETE_CHALLENGE_SUCCESS = "DELETE_CHALLENGE_SUCCESS";
export const DELETE_CHALLENGE_ERROR = "DELETE_CHALLENGE_ERROR";

export const SET_TITLE_DESC = "SET_TITLE_DESC";
