export const PARENT_REGISTER_LOADING = "PARENT_REGISTER_LOADING";
export const PARENT_REGISTER_SUCCESS = "PARENT_REGISTER_SUCCESS";
export const PARENT_REGISTER_ERROR = "PARENT_REGISTER_ERROR";

export const PARENT_REGISTER_2_LOADING = "PARENT_REGISTER_2_LOADING";
export const PARENT_REGISTER_2_SUCCESS = "PARENT_REGISTER_2_SUCCESS";
export const PARENT_REGISTER_2_ERROR = "PARENT_REGISTER_2_ERROR";

export const PARENT_LOGIN_LOADING = "PARENT_LOGIN_LOADING";
export const PARENT_LOGIN_SUCCESS = "PARENT_LOGIN_SUCCESS";
export const PARENT_LOGIN_ERROR = "PARENT_LOGIN_ERROR";

export const CHILD_LOGIN_LOADING = "CHILD_LOGIN_LOADING";
export const CHILD_LOGIN_SUCCESS = "CHILD_LOGIN_SUCCESS";
export const CHILD_LOGIN_ERROR = "CHILD_LOGIN_ERROR";

export const CHILD_REGISTER_LOADING = "CHILD_REGISTER_LOADING";
export const CHILD_REGISTER_SUCCESS = "CHILD_REGISTER_SUCCESS";
export const CHILD_REGISTER_ERROR = "CHILD_REGISTER_ERROR";

export const ALL_FAMILY_LOADING = "ALL_FAMILY_LOADING";
export const ALL_FAMILY_SUCCESS = "ALL_FAMILY_SUCCESS";
export const ALL_FAMILY_ERROR = "ALL_FAMILY_ERROR";
