export const CREATE_REWARD_LOADING = "CREATE_REWARD_LOADING";
export const CREATE_REWARD_SUCCESS = "CREATE_REWARD_SUCCESS";
export const CREATE_REWARD_ERROR = "CREATE_REWARD_ERROR";

export const GET_REWARD_LOADING = "GET_REWARD_LOADING";
export const GET_REWARD_SUCCESS = "GET_REWARD_SUCCESS";
export const GET_REWARD_ERROR = "GET_REWARD_ERROR";

export const ALL_REWARD_LOADING = "ALL_REWARD_LOADING";
export const ALL_REWARD_SUCCESS = "ALL_REWARD_SUCCESS";
export const ALL_REWARD_ERROR = "ALL_REWARD_ERROR";

export const CLAIM_REWARD_LOADING = "CLAIM_REWARD_LOADING";
export const CLAIM_REWARD_SUCCESS = "CLAIM_REWARD_SUCCESS";
export const CLAIM_REWARD_ERROR = "CLAIM_REWARD_ERROR";

export const DELETE_REWARD_LOADING = "DELETE_REWARD_LOADING";
export const DELETE_REWARD_SUCCESS = "DELETE_REWARD_SUCCESS";
export const DELETE_REWARD_ERROR = "DELETE_REWARD_ERROR";

export const SET_TITLE_DESC = "SET_TITLE_DESC";
